from .prometheus_metrics import (
    metrics_service,
    REQUEST_COUNT,
    REQUEST_DURATION,
    ACTIVE_LOANS,
    TOTAL_USERS,
    DOCUMENTS_AVAILABLE,
    LOANS_CREATED,
    LOANS_RETURNED,
    OVERDUE_LOANS,
    KAFKA_MESSAGES_SENT,
    KAFKA_MESSAGES_PROCESSED,
    KAFKA_PROCESSING_ERRORS,
    generate_latest
)

__all__ = [
    "metrics_service",
    "REQUEST_COUNT",
    "REQUEST_DURATION", 
    "ACTIVE_LOANS",
    "TOTAL_USERS",
    "DOCUMENTS_AVAILABLE",
    "LOANS_CREATED",
    "LOANS_RETURNED",
    "OVERDUE_LOANS",
    "KAFKA_MESSAGES_SENT",
    "KAFKA_MESSAGES_PROCESSED",
    "KAFKA_PROCESSING_ERRORS",
    "generate_latest"
]
